name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CACHE_IMAGES_DATE: "2024-05-15"
  CACHE_IMAGES_TAR: ./cache-images.tar

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Copy .env
        run: cp .env.example .env

      # Composer パッケージをインストールする（キャッシュする）
      - name: Cache composer packages
        id: cache-composer-packages
        uses: whywaita/actions-cache-s3@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('./composer.lock') }}
          aws-s3-bucket: composer-cache
          aws-access-key-id: dummy
          aws-secret-access-key: dummy
          aws-region: ap-northeast-1
          aws-endpoint: http://localhost:4566
      - name: Install dependencies
        if: steps.cache-composer-packages.outputs.cache-hit != 'true'
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php82-composer:latest composer install --ignore-platform-reqs
